### TypeScript requires Node.js, which
### Chocolatey will install before TS.
### Learn more: typescriptlang.org/docs




name: Setup TypeScript

on: push

jobs:

  install:

    runs-on: windows-2022

    steps:

      - run: Install TypeScript via PowerShell
        run: choco install typescript

