### TypeScript requires Node.js, which
### Chocolatey will install before TS.
### Learn more: https://typescriptlang.org/docs/handbook/typescript-in-5-minutes.html




name: Setup TypeScript

on: push

jobs:

  install:

    runs-on: windows-2022

    steps:

      - run: Install TypeScript via PowerShell
        run: choco install typescript

