### TypeScript requires Node.js, which
### Chocolatey will install before TS.
### Help: https://typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

### By using this Action, you agree to
### the terms of the Apache License 2.0.
### apache.org/licenses/LICENSE-2.0.txt
name: Setup TypeScript
description: Setup TypeScript along with Node.js and add them to the PATH
branding:
  icon: 'box'
  color: 'white'

on: push

jobs:

  install:

    runs-on: windows-2022

    steps:

      - run: Install TypeScript via PowerShell
        run: choco install nodejs typescript

