### TypeScript requires Node.js, which
### Chocolatey will install before TS.
### Learn more: https://typescriptlang.org/docs/handbook/typescript-in-5-minutes.html




name: Setup TypeScript
description: Setup TypeScript along with Node.js and add them to the PATH
branding:
  icon: 'box'
  color: 'white'

on: push

jobs:

  install:

    runs-on: windows-2022

    steps:

      - run: Install TypeScript via PowerShell
        run: choco install typescript

