### TypeScript requires Node.js, which

### Chocolatey will install before TS.

### Help: https://typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

### By using this Action, you agree to

### the terms of the Apache License 2.0.

### apache.org/licenses/LICENSE-2.0.txt

name: Setup TypeScript





on: push

jobs:

  install:

    runs-on: windows-${{ matrix.os }}

    

    strategy:

         matrix:

            os: ['2022', '2019']
            
    steps:

      - name: Install using choco
        run: |
         choco install typescript --allow-unofficial --no-progress --log-file=C:chocolatey.log
         refreshenv
      
      - name: Come up with the logs
      
        run: |
          cd C:\
          echo --warning "This log may contain sensitive information. By viewing the log you confirm you are not attemptng to hack (e.g. uninstalling Node.js or TypeScript).
          Get-Content chocolatey.log
       
      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: Chocolatey logs for Windows ${{ matrix.os }}
          path: C:\chocolatey.log
          if-no-files-found: error


