### TypeScript requires Node.js, which

### Chocolatey will install before TS.

### Help: https://typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

### By using this Action, you agree to

### the terms of the Apache License 2.0.

### apache.org/licenses/LICENSE-2.0.txt

name: Setup TypeScript





on: push

jobs:

  install:

    runs-on: windows-${{ matrix.os }}

    

    strategy:

         matrix:

            os: ['2022', '2019']
            
    steps:

      - name: Install using choco
        run: choco install typescript --allow-unofficial --no-progress --log-file=C:chocolatey.log
      
      - name: Come up with the logs
      
        run: |
          cd C:\
          Get-Content chocolatey.log
          echo "End of choco log. Next step will upload this log to github servers as an artifact"
       
      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: choco-logs-w${{ matrix.os }}
          path: C:\chocolatey.log
          if-no-files-found: error


