### TypeScript requires Node.js, which

### Chocolatey will install before TS.

### Help: https://typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

### By using this Action, you agree to

### the terms of the Apache License 2.0.

### apache.org/licenses/LICENSE-2.0.txt

name: Setup TypeScript





on: push

jobs:

  install:

    runs-on: ${{ matrix.os }}-latest

    

    strategy:

         matrix:

            os: ['windows', 'macos', 'ubuntu']
            command: ['choco install typescript', 'brew install typescript', 'brew install typescript']

    steps:

      - run: ${{ matrix.command }}


