### TypeScript requires Node.js, which

### Chocolatey will install before TS.

### Help: https://typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

### By using this Action, you agree to

### the terms of the Apache License 2.0.

### apache.org/licenses/LICENSE-2.0.txt

name: Setup TypeScript





on: push

jobs:

  install:

    runs-on: windows-${{ matrix.os }}

    

    strategy:

         matrix:

            os: ['2022', '2019']
            
    steps:

      - name: Install using choco
        run: |
         echo "::group::How the process works"
         echo "This process takes a few seconds to complete. It installs the typescript NuGet Package by using a Windows package manager called Chocolatey (choco for short)."
         echo "::endgroup::"
         echo "::group::GitHub runner info"
         echo "::debug::Microsoft Windows Server ${{ matrix.os }} running on ${{ runner.name }}." "::debug::Architecture: ${{ runner.arch }}" "Pre-installed Tools: ${{ runner.tool_cache	}}"
         choco install typescript --allow-unofficial --no-progress --log-file=C:chocolatey.log
         refreshenv
         cd C:\
         echo "::group::Detailed logs"
         echo "::warning::Stop! This log is for developers only. Do not share any sensitive information since hackers could gain access to your GitHub account."
         Get-Content chocolatey.log
         echo "::endgroup::"
       
      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: Chocolatey logs for Windows ${{ matrix.os }}
          path: C:\chocolatey.log
          if-no-files-found: error


