### TypeScript requires Node.js, which

### Chocolatey will install before TS.

### Help: https://typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

### By using this Action, you agree to

### the terms of the Apache License 2.0.

### apache.org/licenses/LICENSE-2.0.txt

name: Setup TypeScript





on: push

jobs:

  install:

    runs-on: windows-${{ matrix.os }}

    

    strategy:

         matrix:

            os: ['2022', '2019', '2016']
            
    steps:

      - name: Install using choco
        run: choco install typescript --allow-unofficial --no-progress --log-file=C:zchocolatey.log
      
      - name: Come up with the logs
      
        run: |
          cd C:\
          Get-Content chocolatey.log
       
      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: choco-logs-%RANDOM%%RANDOM%%RANDOM%%RANDOM%
          path: C:\chocolatey.log
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`


