name: Setup TypeScript

on: push

jobs:

  install:

    runs-on: windows-2022

    steps:

      - name: Install TypeScript via PowerShell

        run: choco install typescript

      - name: Get version

        run: typescript version
